version: '3.9'

services:

  # Oracle service (label used to access the service container)
  oracle:

    # Docker Hub image: https://hub.docker.com/r/gvenzl/oracle-xe
    image: gvenzl/oracle-xe:21

    # Provide passwords and other environment variables to container
    environment:
      ORACLE_PASSWORD: syspass1
      ORACLE_DATABASE: dualsoft_db
      APP_USER: my_user
      APP_USER_PASSWORD: changeme

    # Forward Oracle port
    ports:
      - 1521:1521

    # Provide healthcheck script options for startup
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 10
